"use client";
import { useEffect, useState } from "react";
import { api } from "../../../lib/api";

type Health = { status: string; db?: string; redis?: string; version?: string; revision?: string; providers?: Record<string, boolean>; notificationQueue?: { pending: number; processing: number; failed: number } };
export default function SettingsPage() {
  const [health, setHealth] = useState<Health | null>(null);
  useEffect(() => { api<Health>("/health/ready").then(setHealth).catch(() => setHealth({ status: "degraded" })); }, []);
  return <div className="space-y-6"><header><p className="eyebrow">Pengaturan sistem</p><h1 className="mt-2 text-3xl font-black">Status Konfigurasi</h1><p className="mt-2 text-sm text-slate-600">Halaman ini hanya menampilkan kesiapan layanan. Secret dan kredensial tidak pernah ditampilkan atau diedit dari browser.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["API",health?.status],["Database",health?.db],["Redis & Worker",health?.redis],["Revisi",health?.revision]].map(([label,value]) => <article key={label} className="medical-card"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className={`mt-3 text-lg font-black ${["ready","up"].includes(String(value)) ? "text-emerald-700" : "text-slate-700"}`}>{value ?? "Memeriksa…"}</p></article>)}</section>{health?.notificationQueue ? <section className="medical-card"><h2 className="text-lg font-black">Antrean notifikasi</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center">{Object.entries(health.notificationQueue).map(([label,value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><b className="text-2xl">{value}</b><span className="block text-xs capitalize text-slate-500">{label}</span></div>)}</div></section> : null}<section className="medical-card"><h2 className="text-lg font-black">Kontrol operasional</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-slate-600"><li>Kelola pengguna melalui Manajemen Pengguna.</li><li>Kelola layanan dan tenaga kesehatan melalui Master Data.</li><li>Kelola protokol Early Warning System melalui Protokol EWS.</li><li>Perubahan secret dilakukan melalui secret manager dan proses deployment.</li></ul></section></div>;
}
